### ISSUE TITLE
Gray bars 🤞

### ISSUE THREAD

**Issue by quillincn** [Kas-tle/IgnoreSecureChat#1]
This resourcepack gonna save my life, those bars are useless and really nerves me. Everything perfect, but can you remove gray bars too? I was tried by myself, but I don't have idea where I can take proper HEX color for that.

**Comment by quillincn** [comment]
I found it, it's ``0xa0a0a0``, not sure about correct way to add it, but im just duplicate original line in ``position color.vsh`` and that's works!

```
            case 0xE84F58:
                vertexColor = vec4(0); //set to invisible
            case 0xa0a0a0:
                vertexColor = vec4(0); //set to invisible
            break;
```

**Comment by Kas-tle** [comment]
This was made primarily for use with Geyser due to the inability to implement secure chat on Bedrock, so we only changed what was needed to make Bedrock players appear normal. Happy you were able to modify it to fit your needs, nonetheless.
